#!/bin/bash
sudo hostnamectl set-hostname LinTroS2

#netplan
sudo cat <<EOT > /etc/netplan/00-installer-config.yaml
network:
	ethernets:
		ens33:
			dhcpv4: true
			match:
				macaddress: 00:0c:29:41:8c:46
			set-name: outside
		ens37:
			addresses:
				- 10.0.0.254/24
			match:
				macaddress: 00:0c:29:41:8c:50
			set-name: lan
		ens38:
			addresses:
				- 192.168.30.254/24
			match:
				macaddress: 00:0c:29:41:8c:5a
			set-name: dmz
	version: 2
EOT

sudo netplan apply

sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -p


# iptables binary
IPT="/sbin/iptables"

# delete old config
$IPT -F
$IPT -X

# set default policy
$IPT -P INPUT DROP
$IPT -P OUTPUT DROP
$IPT -P FORWARD DROP

# allow ongoing connections
$IPT -A INPUT -m conntrack --cstate ESTABLISHED,RELATED -j ACCEPT
$IPT -A OUTPUT -m conntrack --cstate ESTABLISHED,RELATED -j ACCEPT
$IPT -A FORWARD -m conntrack --cstate ESTABLISHED,RELATED -j ACCEPT

# allow loopback
$IPT -A INPUT -i lo -j ACCEPT
$IPT -A OUTPUT -o lo -j ACCEPT

# create own chains
$IPT -N lan_dmz
$IPT -N lan_outside
$IPT -N dmz_outside



# LAN <-> DMZ
$IPT -A FORWARD -i lan -o dmz -j lan_dmz
$IPT -A FORWARD -i dmz -o lan -j lan_dmz

$IPT -A lan_dmz -m conntrack --ctstate RELATED,ESTABLISHED -j LOG --log-prefix "IPTABLES CONN RELATED/ESTABLISHED: "
$IPT -A lan_dmz -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# DNS/ICMP
$IPT -A lan_dmz -p icmp -j ACCEPT
$IPT -A lan_dmz -p tcp --dport domain -j ACCEPT
$IPT -A lan_dmz -p udp --dport domain -j ACCEPT

# http
$IPT -A lan_dmz -p tcp --dport http -j accept
$IPT -A lan_dmz -p tcp --dport 3000 -j ACCEPT
$IPT -A lan_dmz -p tcp --dport 9090 -j ACCEPT
$IPT -A lan_dmz -p tcp --dport 9100 -j ACCEPT

# nfs
$IPT -A lan_dmz -p tcp --dport nfs -j ACCEPT
$IPT -A lan_dmz -p udp --dport nfs -j ACCEPT
$IPT -A lan_dmz -p tcp --dport 2050 -j ACCEPT
$IPT -A lan_dmz -p udp --dport 2050 -j ACCEPT

# Kerberos
$IPT -A lan_dmz -p udp --dport 88 -j ACCEPT
$IPT -A lan_dmz -p udp --dport 749 -j ACCEPT
$IPT -A lan_dmz -p tcp --dport 88 -j ACCEPT
$IPT -A lan_dmz -p tcp --dport 749 -j ACCEPT


# lan -> outside
$IPT -A FORWARD -i lan -o outside -j lan_outside

$IPT -A lan_outside -m conntrack --ctstate RELATED,ESTABLISHED -j LOG --log-prefix "IPTABLES CONN RELATED/ESTABLISHED: "
$IPT -A lan_outside -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# dmz -> outside
$IPT -A FORWARD -i dmz -o outside -j dmz_outside

$IPT -A dmz_outside -m conntrack --ctstate RELATED,ESTABLISHED -j LOG --log-prefix "IPTABLES CONN RELATED/ESTABLISHED: "
$IPT -A dmz_outside -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

#Masquerading
$IPT -t nat -A POSTROUTING -o outside -j MASQUERADE

echo "Konfiguration abgeschlossen."
